DROP TABLE "branch" CASCADE;
DROP TABLE "client" CASCADE;
DROP TABLE "product" CASCADE;
DROP TABLE "coming" CASCADE;
DROP TABLE "picking_sheet" CASCADE;
DROP TABLE "remainder" CASCADE;
DROP TABLE "sale" CASCADE;
DROP TABLE "sale_product" CASCADE;